### ISSUE TITLE
Add support for ERC-223 tokens

### ISSUE THREAD

**Issue by HarryR** [clearmatics/mobius#22]
It is possible to make the mixer support both ERC-223 and ERC-20 tokens as well as Ether in the Mixer contract. It's also possible to make it send Ether to smart contracts too, or send tokens then invoke a method on a smart contract.

In the ERC-223 and ERC-20 case the Mixer calls the `transfer` method of the token.

When the token address is `0` this is synonymous with Ether, if not zero the Mixer must validate the contract exists by calling `extcodesize(addr)`.

ERC-223 tokens also support an optional arbitrary data field.

To make arbitrary smart contract calls the Withdraw caller must specify the `msg.data` field, contract address and Gas limit.

 e.g. `WithdrawToContract(ring_id, tx, ty, ctlist, address, gas, msg_data)`

With this construct you make the Mixer call its self to Deposit again without needing a utility method for every conceivable thing the user may want to do, but it opens up a security hole for anything that relies on `tx.origin` rather than `msg.sender`

All of these parameters need to be included in the hash.

For now, I think it would be good to split the `Mixer.Withdraw` function into multiple variants to avoid convoluted code paths.

 * WithdrawERC20
 * WithdrawERC223
 * WithdrawEther

And maybe functions like:

  * WithdrawEtherTo (recipient address)

**Comment by HarryR** [comment]
Instead of the above approach the contract will use the `tokenFallback` interface from ERC-223.

The tag_x/tag_y point will be extracted from the `bytes data` parameter upon sending tokens to the contract.

The `msg.sender` will be the token address.

The `denomination` will be the `value` parameter.

**Comment by AntoineRondelet** [comment]
This issue tackled in the PR #57 which added support for ERC20 compatible tokens (ERC223 that are ERC20 compatible are thus supported).

I'll close it as I think this is done now. The withdrawal to contracts is not supported though, but this can be subject to another issue/PR if we need it in the future.
