### ISSUE TITLE
Add  code of conduct 

### ISSUE THREAD

**Issue by zoenolan** [clearmatics/mobius#63]

**Comment by AntoineRondelet** [comment]
Isn't it already in https://github.com/clearmatics/mobius/blob/master/CONTRIBUTING.md @zoenolan ?
Do we need to update it ?

**Comment by zoenolan** [comment]
It just was not showing up on https://github.com/clearmatics/mobius/community

**Comment by AntoineRondelet** [comment]
Ah yes indeed. Shall we split the "contributing" file then ?

**Comment by zoenolan** [comment]
I was going to have a look what others do. All our repos have the same issue

**Comment by zoenolan** [comment]
See clearmatics/eth-private-network#1, clearmatics/orbital#33, clearmatics/bn256#3 and clearmatics/asset-token#62
